# Generated by Django 4.1.1 on 2022-09-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='roomname',
        ),
        migrations.AddField(
            model_name='message',
            name='roomid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
